account: Expenses:Unknown
match:
  - comment: 'CO: PACIFIC GAS & EL'
    replace:
      payee: PGE
      posting: |
        Expenses:Utilities:Gas   $0
        Expenses:Utilities:Electric  $0
        Expenses:Fix Me  {{.PostingValue}}
  - comment: 'CO: SAN FRANCISCO WA'
    replace:
      payee: SFPUC
      posting: |
        Expenses:Utilities:Water   $0
        Expenses:Utilities:Sewer  $0
        Expenses:Fix Me  {{.PostingValue}}
  - comment: ATM Withdrawal
    replace:
      payee: Cash Withdrawal
      posting: |
        Expenses:Bank Fees   $3
        Expenses:Fix Me  $0; adjust bank fees as needed
        Assets:Cash
        
        
