package dup

// THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.

import "strings"

var csvText = strings.TrimSpace(`
"integration_src.ledger","10","","2016/03/21","","Local Grocery Store","11","Expenses:Grocery","$","10","",""
"integration_src.ledger","10","","2016/03/21","","Local Grocery Store","12","Liabilities:Credit Card","$","-10","",""
"integration_src.ledger","13","","2016/03/22","","Another Local Grocery Store","14","Expenses:Grocery","$","10","",""
"integration_src.ledger","13","","2016/03/22","","Another Local Grocery Store","15","Liabilities:Another Credit Card","$","-10","",""
"integration_src.ledger","16","","2016/03/25","","Another Local Grocery Store","17","Expenses:Grocery","$","10",""," SuppressAmountDuplicates: 2016/03/22"
"integration_src.ledger","16","","2016/03/25","","Another Local Grocery Store","19","Liabilities:Credit Card","$","-10","",""
"integration_src.ledger","20","","2016/04/21","","Another Local Grocery Store","21","Expenses:Grocery","$","10","",""
"integration_src.ledger","20","","2016/04/21","","Another Local Grocery Store","22","Liabilities:Another Credit Card","$","-10","",""
"integration_src.ledger","23","","2016/05/01","foo","Local Grocery Store","24","Expenses:Grocery","$","15","",""
"integration_src.ledger","23","","2016/05/01","foo","Local Grocery Store","25","Liabilities:Credit Card","$","-15","",""
"integration_src.ledger","26","","2016/05/15","bar","Local Grocery Store","27","Expenses:Grocery","$","20","",""
"integration_src.ledger","26","","2016/05/15","bar","Local Grocery Store","28","Liabilities:Credit Card","$","-20","",""
"integration_src.ledger","29"," SuppressCodeDuplicates: 2016/05/15","2016/05/16","bar","Local Grocery Store","31","Expenses:Grocery","$","22",""," SuppressCodeDuplicates: 2016/05/15"
"integration_src.ledger","29"," SuppressCodeDuplicates: 2016/05/15","2016/05/16","bar","Local Grocery Store","32","Liabilities:Credit Card","$","-22",""," SuppressCodeDuplicates: 2016/05/15"
"integration_src.ledger","33","","2016/05/31","#foo","Another Local Grocery Store","34","Expenses:Grocery","$","25","",""
"integration_src.ledger","33","","2016/05/31","#foo","Another Local Grocery Store","35","Liabilities:Credit Card","$","-25","",""
`)
